=== lathspell/php_test/XML/example.dtd
<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/example.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE root SYSTEM "example.dtd">

    <root>
    ...
    </root>
-->


<!--- Put your DTDDoc comment here. -->
<!ELEMENT root (artikel)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT artikel (price)*>
<!ATTLIST artikel id ID #REQUIRED>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT price (#PCDATA)>

=== lathspell/php_test/XML/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "example.dtd">
<root>
  <artikel id="artikel4">
      <price>40</price>
  </artikel>
  <artikel id="artikel5">
      <price>50</price>
  </artikel>
  <artikel id="artikel6">
      <price>60</price>
  </artikel>
  <artikel id="artikel7">
      <price>70</price>
  </artikel>
</root>
